services:
    bot:
        image: kooldev/php:8.1
        container_name: bot
        working_dir: /bot
        restart: always
        networks:
            - internal
            - nginx_network
        volumes:
            - ".:/bot"
            - "./docker/php/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini"
        links:
            - bot-database
        depends_on:
            - bot-database
        environment:
            - PHP_EXECUTABLE_PATH=/usr/local/bin/php
    bot-nginx:
        image: nginx:alpine
        container_name: bot-nginx
        restart: always
        working_dir: /bot
        networks:
            - internal
            - nginx_network
        ports:
            - "9007:80"
        volumes:
            - .:/bot
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - bot
    bot-composer:
        image: composer:latest
        container_name: bot-composer
        working_dir: /bot
        command: update --ignore-platform-reqs
        volumes:
            - .:/bot
        restart: on-failure
        depends_on:
            - bot
    bot-database:
        image: mariadb:latest
        restart: always
        container_name: bot-database
        working_dir: /bot
        networks:
            - internal
            - nginx_network
        # command: mysqld --skip-grant-tables
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=bot
            - MYSQL_USER=root
            - MYSQL_PASSWORD=password
        volumes:
            - .:/bot
            - ./bot-database:/var/lib/mysql
        ports:
            - "8006:3306"
    bot-redis:
        image: "redis:alpine"
        ports:
            - "${FORWARD_REDIS_PORT:-6383}:6383"
        volumes:
            - bot-redis:/data
        networks:
            - internal
            - nginx_network
        command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81

    app:
        image: node:16-alpine
        working_dir: /app
        volumes:
        - .:/app
        command: sh -c "npm install && npm run build"
    bot-npm:
        image: node:20-alpine
        container_name: bot-npm
        working_dir: /bot
        volumes:
            - ".:/bot"
        depends_on:
            - bot
    adminer:
        image: adminer
        restart: always
        networks:
            - nginx_network
        ports:
            - "8082:8082"
networks:
    nginx_network:
        external: true
    internal:
        driver: overlay
        name: "global"
        attachable: true
        external: true
volumes:
    bot-database:
        driver: local
    bot-redis:
        driver: local
